name: Deploy to App Engine

on:
  workflow_dispatch:

jobs:
  deploy-to-appengine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - id: 'replace-strings'
        run: brave/replace_strings.sh

      - name: npm audit fix
        continue-on-error: true
        run: |
          cd common/node_runner/node_runner/
          npm audit fix

      - id: 'auth'
        uses: 'google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033' # v1.1.1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY}}'
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@5a5f7b85fca43e76e53463acaa9d408a03c98d3a # v2.0.1
        with:
          project_id: 'brave-perf-dashboard'
          version: '453.0.0'
      - name: Set up Python 3 and deploy via script
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.8'
      - run: python dashboard/bin/deploy --promote app.yaml api.yaml upload.yaml upload-processing.yaml dispatch.yaml cron.yaml index.yaml
        env:
          VERSION: ${{github.run_number}}
